## PCA Demo


In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
#Generate a dummy dataset.
X = np.array([[1,2,2], [1,2,1], [3,2,1], [1,2,3]])
C_X = (1/2)*np.cov(X)

C_X

array([[ 0.16666667,  0.08333333, -0.25      ,  0.25      ],
       [ 0.08333333,  0.16666667,  0.        ,  0.        ],
       [-0.25      ,  0.        ,  0.5       , -0.5       ],
       [ 0.25      ,  0.        , -0.5       ,  0.5       ]])

In [6]:
eigenvalues, eigenvectors = la.eig(C_X)
print(eigenvalues)

print(eigenvectors)

[ 1.13064703e+00+0.j  2.02686303e-01+0.j -2.10683520e-19+0.j
 -1.06021622e-16+0.j]
[[-0.34646195  0.39075746  0.06182002 -0.8524843 ]
 [-0.02995064  0.90403804 -0.03091001  0.42624215]
 [ 0.66297326  0.12252312  0.72070147 -0.23244673]
 [-0.66297326 -0.12252312  0.68979146  0.19379542]]


In [12]:
np.sum(eigenvectors[0]*eigenvectors[3])

0.05925355395640827

In [9]:
eigenvectors[3]

array([-0.66297326, -0.12252312,  0.68979146,  0.19379542])

### Principal components of X are the e-vectors of XX^T (P=[p_i])

### The i-th diagonal value of C_Y is the varaince of X along p_i